/* ⚠️ RETIRED STALE COPY — do not edit this file. (2026-06-10 audit)
   The LIVE pet widget is `pet-widget.js` at the REPO ROOT — that's what index.html loads.
   This older duplicate predated the maximize / photo / suggestion-chip features and existed
   only to confuse future edits (it nearly did). It's safe to delete this file entirely:
       del "E:\Documents\Claude\Projects\Personal OS\Eggie-Personal-OS\pet-widget\pet-widget.js"
   ⚠️ The IMAGES in this folder (Sprite Sheet.png, Screenshot 2026-06-02 202234.png) ARE used
   by the app, the manifest and the service worker — keep those. */
